test/models/user_test.rb

- modified:   test/models/user_test.rb
**Changes**
1. Added basic model test
No changes to spec files -- raking red

Unit test setup

---

app/assets/stylesheets/components/_category-card.scss
app/assets/stylesheets/components/_feed-card.scss
app/assets/stylesheets/components/_index.scss
app/controllers/pages_controller.rb
app/views/pages/style_guide.html.erb
config/routes.rb
db/schema.rb
spec/models/collection_spec.rb

**Files Modified: 5 Files**
modified:   app/assets/stylesheets/components/_index.scss
modified:   app/controllers/pages_controller.rb
modified:   config/routes.rb
modified:   db/schema.rb
modified:   spec/models/collection_spec.rb
**Files Added: 3 Files**
- new-file: app/assets/stylesheets/components/_category-card.scss
- new-file: app/assets/stylesheets/components/_feed-card.scss
- new-file: app/views/pages/style_guide.html.erb
**Changes**
1. et up style guide page and routeS
2. Added the scss files for category card and feed card
No changes to spec files

Create the styleguide pages

---

README.md
app/controllers/application_controller.rb
app/models/add_meme_to_rarity.rb
app/models/category.rb
app/models/collection.rb
app/models/comment.rb
app/models/meme.rb
app/models/rarity.rb
app/models/user.rb
app/models/user_following.rb
db/migrate/20200302232135_create_collection_followings.rb
db/migrate/20200302232331_create_category_followings.rb
db/migrate/20200302232854_create_user_followings.rb
db/migrate/20200303021659_add_username_to_user.rb
db/schema.rb
db/seeds.rb
spec/models/collection_spec.rb

- All the models (added associations and validations);
+ migrations to retrieve specific keys.
**To do**
rails db:drop / db:create / db:migrate (do not db:reset, won't work)

models associations and validations up for testing

---

config/routes.rb

Routes set up

---

app/controllers/memes_controller.rb
app/views/memes/edit.html.erb
app/views/memes/index.html.erb
app/views/memes/new.html.erb
app/views/memes/show.html.erb
config/routes.rb
test/controllers/memes_controller_test.rb

**New file**
- MemesController: set up with basic methods;
- Memes Views: default

Meme controller set up with basic methods, empty meme views set up

---

app/controllers/memes_controller.rb
app/views/memes/edit.html.erb
app/views/memes/index.html.erb
app/views/memes/new.html.erb
app/views/memes/show.html.erb
config/routes.rb
test/controllers/memes_controller_test.rb

**Modified file**
- Routes: deleted duplicates created by rails g controller.

Deleted useless routes

---

app/controllers/users_controller.rb
app/models/collection.rb
app/views/users/show.html.erb
config/routes.rb
test/controllers/users_controller_test.rb

**New Files**
- UsersController with basic show method;
- User show page (view);

UsersController set up with show method & view

---

app/controllers/collections_controller.rb
app/models/category_following.rb
app/models/collection_following.rb
app/views/collections/edit.html.erb
app/views/collections/new.html.erb
app/views/collections/show.html.erb
db/seeds.rb
test/controllers/collections_controller_test.rb

**Modified**
- User Model;
- Collection, CollectionFollowing models;
- Category, CategoryFollowing models.

Associations fixed

---

app/assets/stylesheets/components/_index.scss
app/assets/stylesheets/components/_meme-card.scss
app/views/pages/style_guide.html.erb
app/views/shared/cards/_meme_card.html.erb
app/views/shared/sidebar/_left_sidebar.html.erb
app/views/shared/sidebar/_sidebar_main_menu.html.erb
app/views/shared/sidebar/_sidebar_user_info_card.html.erb
db/schema.rb

Edited style guide and added folders and erb files in views folder

Edited style guide and added folders and erb files in views folder

---

app/views/memes/index.html.erb

Created the components on the meme index page

Created the meme index layout

---

app/views/memes/show.html.erb

Created the components on meme show page

Created meme show layout

---

app/models/collection.rb
app/models/meme.rb
db/seeds.rb
spec/models/category_spec.rb
spec/models/collection_spec.rb
spec/models/meme_spec.rb
spec/models/user_spec.rb
test/models/user_test.rb

- modified:   app/models/collection.rb
- modified:   app/models/meme.rb
- modified:   spec/models/category_spec.rb
- modified:   spec/models/collection_spec.rb
- modified:   spec/models/meme_spec.rb
- modified:   spec/models/user_spec.rb
**Changes**
1. Fixed test to reflect the model builds
Changes to spec files -- raking red on following tests

Model testing

---

README.md
app/models/category.rb
app/models/category_following.rb
app/models/collection.rb
app/models/collection_following.rb
app/models/user.rb
db/migrate/20200302232135_create_collection_followings.rb
db/schema.rb
db/seeds.rb

***Modified***
- +/- all models...
**To do**
/!!\ Delete your schema file
Run rails db:reset

Models' associations fixed

---

app/views/memes/show.html.erb
app/views/shared/cards/_comment_card.html.erb
app/views/shared/components/_comment_form.html.erb
db/seeds/categories.yml
db/seeds/users.yml

Edited layout for 
comment_card.html.erb
and 
comment_form.html.erb

Edited layout for meme-comment-card and meme-comment-form

---

db/seeds.rb

- modified:   db/seeds.rb
**Changes**
1. Added seed for each model in seeds

Add new seeds for testing

---

app/controllers/categories_controller.rb
app/controllers/collections_controller.rb
app/views/categories/index.html.erb
app/views/categories/new.html.erb
app/views/categories/show.html.erb
config/routes.rb
test/controllers/categories_controller_test.rb

**New file**
- CategoriesController

Category controller basic set up

---

app/assets/stylesheets/components/_category-card.scss
app/controllers/memes_controller.rb
app/views/memes/index.html.erb
app/views/shared/_navbar.html.erb
app/views/shared/cards/_category_card.html.erb
app/views/shared/components/_searchform.html.erb
app/views/shared/sidebar/_left_sidebar.html.erb
config/routes.rb
db/seeds.rb

- memes controller: added top_categories method
- meme.index.html.erb: added top_categories cards into carousel
- seeds.rb: added new categories 
**New files**
- category-card.scss
**TO DO**
Run rails db:reset

Added top_categories method to memes controller

---

app/controllers/memes_controller.rb
app/views/memes/index.html.erb
db/seeds.rb

- MemesController: defined private method "top_three_users" to retrieve the top three users based on their dank_rank.total_score / added @top_three_users to the index;
- Seeds, all users have a dank_rank (hardcoded for now) + added a 4th user;
- Memes index: test for @top_three_users in leaderboard.
**TO DO**
Run rails db:reset

Top three users retrieved in memescontroller

---

app/controllers/memes_controller.rb
db/seeds.rb

- Memes controller: new private method top_three_memes + added @top_three_memes in index;
- Seed: added hardcoded rarity total_score.
**TO DO**
Run rails db:reset

Top three memes ready

---

app/controllers/memes_controller.rb

**Modified**
- MemeController: on meme create method, added Rarity.create! and implement default rarity.total_score of 0.

Made sure each new meme got a default rarity total_score when created

---

.gitignore
.vscode/settings.json
Gemfile
Gemfile.lock
app/controllers/memes_controller.rb
app/models/meme.rb
app/views/memes/new.html.erb
config/environments/development.rb
config/storage.yml
db/migrate/20200305005208_create_active_storage_tables.active_storage.rb
db/schema.rb

Added the meme new page and related logic.
Implemented cloudinary functionality into meme new page.
------
modified:   Gemfile
modified:   Gemfile.lock
modified:   app/controllers/memes_controller.rb
modified:   app/models/meme.rb
modified:   app/views/memes/new.html.erb
modified:   config/environments/development.rb
modified:   config/storage.yml
modified:   db/schema.rb

Frontend meme new

---

.gitignore
.vscode/settings.json
Gemfile
Gemfile.lock
app/controllers/memes_controller.rb
app/models/meme.rb
app/views/memes/_meme_form.html.erb
app/views/memes/edit.html.erb
app/views/memes/new.html.erb
config/environments/development.rb
config/storage.yml
db/migrate/20200305005208_create_active_storage_tables.active_storage.rb
db/schema.rb

Added meme edit page
Added: gem 'cloudinary', '~> 1.12.0'
Run: bundle
NEED TO ADD: Cloudinary API key to env file
Run: rails active_storage:install
Run: rails db:migrate

Frontend meme edit

---

app/controllers/categories_controller.rb
app/views/categories/show.html.erb
app/views/shared/sidebar/_left_sidebar.html.erb

Added category show page

---

app/views/categories/index.html.erb

Added category index page

---

app/views/collections/show.html.erb
app/views/devise/registrations/edit.html.erb
app/views/devise/registrations/new.html.erb
app/views/devise/sessions/new.html.erb

Updated meme collection show page layout

Updated meme collection show page layout

---

app/models/dank_rank.rb
db/seeds.rb

quick fix to db seed

---

app/models/dank_rank.rb
app/models/meme.rb
app/models/user.rb
config/environments/development.rb
config/environments/production.rb
db/seeds.rb
db/seeds/categories.yml
db/seeds/memes.yml
db/seeds/users.yml
test/fixtures/users.yml

- modified:   app/models/dank_rank.rb
- modified:   db/seeds.rb
- modified:   db/seeds/categories.yml
- modified:   db/seeds/memes.yml
**Changes**
1. mostly seed file

New seed files

---

app/controllers/memes_controller.rb
app/models/meme.rb
app/views/memes/_meme_form.html.erb
config/routes.rb

- MemesController: create method;
- _meme_form
- Meme model

New meme form now works with existing category or new category creation

---

.gitignore
db/seeds/categories.yml
db/seeds/memes.yml

Added memes with images and categories to seed data

Added memes with categories in seed data

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/components/_interface.scss
app/assets/stylesheets/components/_left-sidebar.scss
app/assets/stylesheets/components/_meme-window.scss
app/assets/stylesheets/components/meme_cards/_meme-feed-card.scss
app/controllers/pages_controller.rb
app/views/memes/_meme_edit_left_sidebar.html.erb
app/views/memes/_meme_preview.html.erb
app/views/memes/new.html.erb
app/views/pages/dashboard_template.html.erb
config/routes.rb

modified:   app/assets/stylesheets/application.scss
modified:   app/assets/stylesheets/components/_interface.scss
modified:   app/assets/stylesheets/components/_left-sidebar.scss
modified:   app/assets/stylesheets/components/_meme-window.scss
modified:   app/assets/stylesheets/components/meme_cards/_meme-feed-card.scss
modified:   app/controllers/pages_controller.rb
modified:   app/views/memes/new.html.erb
modified:   config/routes.rb
**Changes**
1. Created a front end scaffold

implemented a front end scaffold

---

app/assets/stylesheets/components/_interface.scss
app/views/categories/show.html.erb
app/views/collections/index.html.erb
app/views/collections/show.html.erb
app/views/memes/_meme_feed_card_grid.html.erb
app/views/memes/_meme_form.html.erb
app/views/memes/show.html.erb
app/views/pages/dashboard_template.html.erb
app/views/shared/cards/_meme_card.html.erb
app/views/users/show.html.erb
config/routes.rb

Added collection index page
Changed collection show page

Added collection index page

---

app/controllers/likes_controller.rb
app/controllers/users_controller.rb
app/javascript/packs/indexCollectFormValidation.js
app/views/categories/show.html.erb
app/views/collections/show.html.erb
app/views/memes/_meme_show_meme_view.html.erb
app/views/memes/index.html.erb
test/controllers/likes_controller_test.rb

Modified:
- Index pages (yielding js script)
- new js pack for indexes page

JS validations on collect form for indexes

---

app/assets/stylesheets/components/right_side_bar/_actions.scss
app/assets/stylesheets/components/right_side_bar/_comments.scss
app/assets/stylesheets/components/right_side_bar/_creator.scss
app/controllers/categories_controller.rb
app/views/categories/show.html.erb
app/views/memes/_meme_edit_left_sidebar.html.erb
app/views/memes/show.html.erb
app/views/shared/_navbar.html.erb
app/views/shared/sidebar/_left_sidebar.html.erb
app/views/users/_meme_show_card.html.erb
app/views/users/show.html.erb

Fixed: The meme card on other views where the collection form would break unless given the Collect.new from the controller

Friday hotfix for production push

---

app/views/likes/create.js.erb
app/views/likes/destroy.js.erb

- Views, likes, js create and destroy.

Ajaxed likes now works on index page as well

---

Gemfile
Gemfile.lock
app/controllers/memes_controller.rb
app/models/meme.rb
app/views/categories/index.html.erb
app/views/shared/components/_search_form.html.erb

- Added PG search to meme.rb
- Added meme search to MemesController

Implemented meme search

---

app/controllers/api/v1/base_controller.rb
app/controllers/api/v1/users_controller.rb
app/controllers/users_controller.rb
app/javascript/packs/ajaxDankBoard.js
app/views/api/v1/users/index.json.jbuilder
app/views/api/v1/users/show.json.jbuilder
app/views/layouts/application.html.erb
app/views/shared/components/_user_sidebar_info.html.erb
config/routes.rb

**New files**
- Every new "api" directory (controllers & views);
- App/JS/Packs: ajaxDankBoard;
- Routes (new api routes);
- View/shared/components user_side_info_bar: added data-set.

User info side bar automatic refresh

---

app/assets/stylesheets/components/left_side_bar/_user-sidebar-info.scss
app/models/dank_rank.rb
app/models/user.rb
app/views/shared/components/_user_sidebar_info.html.erb
db/seeds.rb

modified:   app/assets/stylesheets/components/left_side_bar/_user-sidebar-info.scss
modified:   app/models/dank_rank.rb
modified:   app/models/user.rb
modified:   app/views/shared/components/_user_sidebar_info.html.erb
modified:   db/seeds.rb
**Changes**
1. Implemented dank raning system
2.Dank rank bar reflected in view
3. Updated seed file for the new dank system
```rails db:seed```

completed dank rank functionality. aww yiss

---

app/controllers/api/v1/base_controller.rb
app/controllers/api/v1/users_controller.rb
app/controllers/memes_controller.rb
app/controllers/users_controller.rb
app/javascript/packs/ajaxDankBoard.js
app/views/api/v1/users/index.json.jbuilder
app/views/api/v1/users/show.json.jbuilder
app/views/layouts/application.html.erb
app/views/memes/news.html.erb
app/views/memes/trending.html.erb
app/views/shared/_navbar.html.erb
app/views/shared/components/_user_sidebar_info.html.erb
config/routes.rb

- MemesController: trending + news methods rendering rarest and newest memes;
- Routes: /memes/trending & /memes/news;
- Views/shared/components: navbar (added the links)
**New files**
- Views/Memes/ trending & news (same model as index)

Added trending and fresh memes

---

app/javascript/packs/ajaxDankBoard.js
app/views/api/v1/users/show.json.jbuilder

**Modified**
- JS/packs/ajaxDank

Updated dank refresh with new user side bar html

---

app/assets/stylesheets/components/_index.scss
app/assets/stylesheets/components/meme_window/_meme-window.scss
app/assets/stylesheets/components/right_side_bar/_comments.scss
app/assets/stylesheets/components/right_side_bar/_meme-info-section.scss
app/views/memes/show.html.erb
app/views/shared/atoms/_comment_strip.html.erb
app/views/shared/components/_meme_comments.html.erb
app/views/shared/components/_meme_info.html.erb
app/views/shared/sidebars/_meme_right_sidebar.html.erb

- Updated comments section color, border, spacing
- Minor html updates
- Updated Meme Show page center content background

Updated Meme show page styling

---

app/controllers/collections_controller.rb
app/controllers/likes_controller.rb
app/controllers/users_controller.rb
app/models/dank_rank.rb
app/models/user.rb
app/views/shared/_navbar.html.erb

modified:   app/controllers/collections_controller.rb
modified:   app/controllers/likes_controller.rb
modified:   app/controllers/users_controller.rb
modified:   app/models/dank_rank.rb
modified:   app/models/user.rb
modified:   app/views/shared/_navbar.html.erb
**Changes**
1. User for both sides will have an updated dank rank on following actions:
liking, following, unfollowing, collecting, creating, following collection, following category

Completed dank rank action functionality

---

app/controllers/collections_controller.rb
app/controllers/likes_controller.rb
app/controllers/users_controller.rb
app/javascript/packs/ajaxDankBoard.js
app/models/dank_rank.rb
app/models/user.rb
app/views/layouts/application.html.erb
app/views/shared/_navbar.html.erb

modified:   app/javascript/packs/ajaxDankBoard.js
modified:   app/views/layouts/application.html.erb
**Changes**
1. Added a dynamic assignment of API url for production

Dynamic api url

---

app/javascript/packs/memesChart.js
app/views/memes/_meme_catcol_card.html.erb

- JS/packs/memeChart: dynamic API url;
- Views/categories/show: changed hardcoded like to dynamic rendering + ajax

Quick fixes

---

app/assets/stylesheets/components/_right-sidebar.scss
app/views/memes/index.html.erb
app/views/shared/components/_categories_carousel.html.erb
app/views/shared/components/_leaderboard.html.erb

Added some comments to changes

Index background colour update

---

app/views/memes/_meme_show.html.erb

**Modified**
- View/memes/show: changed "Back" link

Fixed back link on meme show page

---

app/views/shared/atoms/_comment_strip.html.erb

Changed comment date
Used helper
time_ago_in_words(comment.created_at)

Converted comment date to time ago

---

app/controllers/collects_controller.rb
app/views/collections/show.html.erb

**Modified**
- Collect controller;
- Views/collections/show;

New destroy collect (=uncollect) functionality + link on collection

---

app/javascript/packs/ajaxDankBoard.js

Commented out bootstrap import on AjaxDankRank

Found the messy line

---

app/assets/stylesheets/config/_fonts.scss

- modified:   app/assets/stylesheets/config/_fonts.scss
**Changes**
1. Linked up from google fonts the ubuntu typeface

Added ubuntu font to stylesheet

---

app/javascript/packs/memesChart.js
app/views/collects/create.js.erb
app/views/layouts/application.html.erb
app/views/shared/sidebars/_left_sidebar.html.erb
app/views/shared/sidebars/_left_sidebar_mycollect.html.erb

**Modified**
- Left sidebar: "my collections" part is now a partial;
- Views/collects/create.js;
+ Quick fix about "environment" for js packs.
**New**
- Partial for "my collections".

My collections ajaxed

---

app/javascript/packs/ajaxDankBoard.js
app/views/shared/components/_user_sidebar_info.html.erb

- Aligned dank triangle scores in right sidebar by, placing number scores into a div under circle icon.

Vertical aligment of dank triangle scores

---

app/controllers/memes_controller.rb
app/javascript/packs/memesChart.js
app/views/collects/create.js.erb
app/views/layouts/application.html.erb
app/views/memes/_meme_show.html.erb
app/views/memes/edit.html.erb
app/views/shared/sidebars/_left_sidebar.html.erb
app/views/shared/sidebars/_left_sidebar_mycollect.html.erb
app/views/users/show.html.erb

**Modified**
- Memes controller: implement complete destroy method (with relative tables);
- Meme show page (delete and edit buttons to right path);
- Meme edit page renders updated form;
- Quick fix on user's profile: used to break "my collections" if a one was empty after a delete.

Meme delete and edit

---

app/views/shared/components/_leaderboard_user_index.html.erb

User index page: 
- added 3 more leaderboards (engagement, collection, creativity)

Finished user index page

---

app/controllers/collects_controller.rb
app/views/collections/show.html.erb
app/views/collects/destroy.js.erb

**Modified**
- View/collections/show: remote true on link to delete + js selector;
- CollectsController: deleted redirect_to;
**New**
- destroy.js.erb (ajax file)

Uncollecting a meme is now ajaxed

---

app/assets/stylesheets/components/right_side_bar/_leaderboard.scss
app/controllers/api/v1/users_controller.rb
app/controllers/memes_controller.rb
app/controllers/users_controller.rb
app/javascript/packs/liveLeaderboard.js
app/views/api/v1/users/leaderboard.json.jbuilder
app/views/api/v1/users/stats.json.jbuilder
app/views/memes/index.html.erb
app/views/shared/components/_leaderboard.html.erb
app/views/users/_leaderboard_users_index.html.erb
app/views/users/_top_tep_users.html.erb
app/views/users/_user.html.erb
app/views/users/_users_list.html.erb
app/views/users/index.html.erb
config/routes.rb

**Modified**
- Views: user index and meme index leaderboards files;
- Controllers/API/UsersController: new top six method;
**New**
- User leaderboard partials;
- JS/Packs: liveLeaderboard => implement live rendering of leaderboard.

Live rendering of leaderboard

---

app/views/shared/atoms/_comment_strip.html.erb
app/views/shared/components/_meme_comments.html.erb

**Modified**
- Comment_strip partial.

Delete comments polish

---

app/assets/stylesheets/components/right_side_bar/_leaderboard.scss
app/controllers/api/v1/users_controller.rb
app/controllers/categories_controller.rb
app/controllers/memes_controller.rb
app/controllers/users_controller.rb
app/javascript/packs/liveLeaderboard.js
app/views/api/v1/users/leaderboard.json.jbuilder
app/views/api/v1/users/stats.json.jbuilder
app/views/memes/index.html.erb
app/views/shared/_navbar.html.erb
app/views/shared/atoms/_comment_strip.html.erb
app/views/shared/components/_leaderboard.html.erb
app/views/shared/components/_meme_comments.html.erb
app/views/users/_leaderboard_users_index.html.erb
app/views/users/_top_tep_users.html.erb
app/views/users/_user.html.erb
app/views/users/_users_list.html.erb
app/views/users/index.html.erb
config/routes.rb

**Modified**
- Controllers skip authentication;
- Navbar partial.

Authentication guards

---

app/controllers/comments_controller.rb
app/models/dank_rank.rb
app/views/memes/index.html.erb
app/views/shared/components/_leaderboard.html.erb
app/views/shared/sidebars/_left_sidebar_login.html.erb

modified:   app/controllers/comments_controller.rb
modified:   app/models/dank_rank.rb
modified:   app/views/memes/index.html.erb
modified:   app/views/shared/components/_leaderboard.html.erb
modified:   app/views/shared/sidebars/_left_sidebar_login.html.erb
**Changes**
1. Had to remove the real time leader board as it was crashing app
2. added paddings to sidebars

Minor tweaks to project to make it ready for push to production

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/components/_index.scss
app/assets/stylesheets/components/meme_cards/_meme-collection-card.scss
app/assets/stylesheets/components/user_dashboard/_account-dashboard.scss
app/assets/stylesheets/components/user_dashboard/_user-dashboard-window.scss
app/javascript/packs/application.js
app/views/memes/_meme_feed_card.html.erb
app/views/shared/components/_like_toggle.html.erb
app/views/shared/components/_user_sidebar_info.html.erb
app/views/users/show.html.erb
app/views/users/show/_user_show_account.html.erb
app/views/users/show/_user_show_collections.html.erb
app/views/users/show/_user_show_memes.html.erb
app/views/users/show/_user_show_metrics.html.erb
package.json
yarn.lock

- modified:   app/assets/stylesheets/components/_index.scss
- modified:   app/assets/stylesheets/components/user_dashboard/_account-dashboard.scss
- modified:   app/views/users/show.html.erb
- modified:   app/views/users/show/_user_show_account.html.erb
- modified:   app/views/users/show/_user_show_collections.html.erb
- modified:   app/views/users/show/_user_show_memes.html.erb
- modified:   app/views/users/show/_user_show_metrics.html.erb
**Files Added: 2 Files**
- new file:   app/assets/stylesheets/components/meme_cards/_meme-collection-card.scss
**Changes**
1. Changed the user dashboard layout

User dashboard rework

---

app/views/memes/index.html.erb
app/views/shared/atoms/_comment_strip.html.erb
app/views/shared/components/_meme_comments.html.erb

- modified:   app/views/shared/atoms/_comment_strip.html.erb
- modified:   app/views/shared/components/_meme_comments.html.erb
**Changes**
1. combined Juliette's and Daniel's comment layouts. trashcan now on bottom right of comment.
Partial solution for eal time update of comment removal still not there :(

Comment combine

---

app/controllers/users_controller.rb
app/views/memes/index.html.erb
app/views/users/_leaderboard_users_index.html.erb

**Modified**
- UsersController: new top methods for creation, collection and engagement + return those to the index page.

Added top creation scores, top collection scores, top engagement scores

---

app/assets/stylesheets/components/_navbar.scss
app/assets/stylesheets/components/left_side_bar/_user-sidebar-info.scss
app/views/layouts/application.html.erb
app/views/memes/index.html.erb
app/views/shared/components/_user_sidebar_info.html.erb

**Modified**
- Navbar partial (html & css);
- User side bar indo (html & css);

Navbar polished

---

app/assets/stylesheets/components/right_side_bar/_leaderboard.scss
app/views/memes/index.html.erb
app/views/shared/components/_users_list.html.erb
app/views/users/show.html.erb

**Modified**
- Leaderboard (side bar): html & css;
- User show page left side bar: html (new padding to match new logo display).

Fixed small bugs post merge

---

app/assets/stylesheets/components/right_side_bar/_leaderboard.scss
app/javascript/packs/liveLeaderboard.js
app/views/api/v1/users/leaderboard.json.jbuilder
app/views/memes/index.html.erb
app/views/shared/components/_users_list.html.erb
app/views/users/show.html.erb
app/views/users/show/_user_show_metrics.html.erb

**Modified**
- JS/Packs: liveLeaderboard.js (now render the new layout);
- Views/api/v1/leaderboard: added avatar link.

Leaderboard refresh update

---

app/assets/stylesheets/components/right_side_bar/_leaderboard.scss
app/javascript/packs/liveLeaderboard.js
app/views/api/v1/users/leaderboard.json.jbuilder
app/views/memes/index.html.erb
app/views/memes/news.html.erb
app/views/memes/trending.html.erb
app/views/shared/components/_users_list.html.erb
app/views/users/show.html.erb
app/views/users/show/_user_show_metrics.html.erb

**Modified**
- Views/memes/new: added js pack at the end;
- Views/memes/trending: added js pack at the end.

Added liveLeaderboard pack on every page displaying leaderboard

---

app/views/shared/components/_leaderboard_user_index.html.erb
app/views/shared/components/_users_list_collection.html.erb
app/views/shared/components/_users_list_creation.html.erb
app/views/shared/components/_users_list_engagement.html.erb

Applied leaderboards' algorithms on user index page

Update leaderboard by using different methods

---

app/assets/stylesheets/components/_index.scss
app/assets/stylesheets/components/_meme-form.scss
app/assets/stylesheets/pages/_index.scss
app/assets/stylesheets/pages/_new.scss
app/views/memes/_meme_upload.html.erb

**Modified**
- Meme_form partial (html);
**New**
- _meme-form partial (css).

Improved upload a meme page & form

---

app/models/rarity.rb
app/views/shared/components/_users_list.html.erb
app/views/users/show.html.erb

- modified:   app/models/rarity.rb
- modified:   app/views/shared/components/_users_list.html.erb	
- modified:   app/views/users/show.html.erb
**Changes**
1. Fixed rarity not working
2. Corrected new user avatar on leader board
3. changed view so you cannot see other users dashboard

Minor tweaks before going pushing to production

---

app/assets/stylesheets/components/_index.scss
app/assets/stylesheets/components/user_dashboard/_categories_window.scss
app/views/categories/index.html.erb

Polished categories index page:
- Used plain hashtag 
- Removed count number for each category
- Changed background color with the site theme color
- Added overflow to categories list
- Added opacity to hashtags

Categories index

---

app/javascript/packs/ajaxDankBoard.js
app/views/shared/components/_user_sidebar_info.html.erb
app/views/users/show.html.erb
app/views/users/show/_user_show_account.html.erb

Updated right side bar in both HTML and JS to clean layout

Updated level number location in left side-bar

---

app/assets/stylesheets/components/_categories-carousel.scss
app/assets/stylesheets/components/right_side_bar/_leaderboard.scss
app/views/memes/index.html.erb
app/views/shared/components/_categories_carousel.html.erb

Modified meme index page:
- Removed categories' count number
- Added box-shadow to the scroller
- Turned "All Categories" into a button

Polished top categories layout on meme index page

---

app/assets/stylesheets/components/_meme-card.scss
app/javascript/packs/collectFormValidation.js
app/javascript/packs/indexCollectFormValidation.js
app/javascript/packs/memeCard.js
app/views/collections/_collection_form.html.erb
app/views/collects/create.js.erb
app/views/comments/create.js.erb
app/views/comments/destroy.js.erb
app/views/likes/create.js.erb
app/views/likes/destroy.js.erb
app/views/memes/_meme_card.html.erb
app/views/memes/_meme_card_overlay.html.erb
app/views/shared/components/_meme_badge.html.erb

**Modified**
- Ajax files (App/views: like/comment/collect create and destroy);
- Meme-card (partials & class/data-set added);
- Overlay-form;

Re-ajax meme card

---

app/assets/stylesheets/components/_meme-card.scss
app/javascript/packs/collectFormValidation.js
app/javascript/packs/indexCollectFormValidation.js
app/javascript/packs/memeCard.js
app/views/collections/_collection_form.html.erb
app/views/collects/create.js.erb
app/views/comments/create.js.erb
app/views/comments/destroy.js.erb
app/views/likes/create.js.erb
app/views/likes/destroy.js.erb
app/views/memes/_meme_card.html.erb
app/views/memes/_meme_card_overlay.html.erb
app/views/shared/components/_meme_badge.html.erb

**Modified**
- App/views/collect/create.
- SCSS alert file.

Sweet alert for collect

---

app/assets/stylesheets/components/_left-sidebar.scss
app/assets/stylesheets/components/_sweet-alert-stylings.scss
app/views/categories/show.html.erb
app/views/collections/show.html.erb
app/views/collects/create.js.erb

**Modified**
- My collection show page (added data-set to retrieve div).

Uncollect a card reajaxed

---

app/assets/stylesheets/components/_left-sidebar.scss
app/assets/stylesheets/components/_sweet-alert-stylings.scss
app/views/categories/show.html.erb
app/views/collections/show.html.erb
app/views/collects/create.js.erb

**Modified**
- View, partials, left-side-bar html

Removed lvl up test link

---

app/controllers/categories_controller.rb
app/controllers/memes_controller.rb
app/controllers/users_controller.rb
app/views/shared/sidebars/_left_sidebar.html.erb

**Modified**
- MemesController, UsersControllers, CategoriesControllers: improved top_tens methods.

Improved top users algorithms so that it includes xp

---

app/assets/stylesheets/components/_meme-form.scss
app/assets/stylesheets/components/_navbar.scss
app/assets/stylesheets/config/_fonts.scss
app/views/memes/_meme_upload.html.erb
app/views/memes/new.html.erb
app/views/shared/_navbar.html.erb
app/views/shared/sidebars/_right_sidebar.html.erb

Added meme upload functionality and layout

New meme rework

---

app/views/shared/components/_meme_info.html.erb

**Modified**
- _meme_info partial (right sidebar of comment section).

Adapted comment section to new right sidebar layout

---

app/assets/stylesheets/components/user_dashboard/_account-dashboard.scss

**Modified**
- User account scss

Fix user metrics section height

---

app/controllers/memes_controller.rb
config/environments/production.rb

**Modified**
- MemesController: skip force SSL for new meme page.
+ config production

Fix for SSL issue on upload preview

---

db/seeds/users.yml

Updated right side bar in both HTML and JS to clean layout

Added unique seed user profile image urls

---

app/views/shared/atoms/_comment_strip.html.erb
app/views/shared/atoms/_user_avatar.html.erb

**Modified**
- Comment strip & user's avatar partials

User's avatar fix on comments section
